name: intl_gen_runner
description: The intl-utils gen wrapper.
version: 0.0.2
homepage: https://github.com/Lochinor/intl_gen
repository: https://github.com/Lochinor/intl_gen
documentation: https://github.com/Lochinor/intl_gen
issue_tracker: https://github.com/Lochinor/intl_gen/issues

publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build: ^2.0.0
  intl_utils:
    git:
      url: https://github.com/Lochinor/intl_utils.git

dev_dependencies:
  lints: any
  build_test: ^2.0.0