name: intl_gen_runner
description: The intl-utils gen wrapper.
version: 5.8.0
homepage: https://github.com/Lochinor/intl_utils
repository: https://github.com/Lochinor/intl_utils
documentation: https://github.com/Lochinor/intl_utils
issue_tracker: https://github.com/Lochinor/intl_utils

publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build: ^2.0.0
  intl_utils:
    git:
      url: https://github.com/Lochinor/intl_utils.git

dev_dependencies:
  lints: any
  build_test: ^2.0.0